// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdugxslfoujddlbkvvak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdWd4c2xmb3VqZGRsYmt2dmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjMwMzksImV4cCI6MjA2MzgzOTAzOX0.V1CflAVNQGZyjl36gs4mzHY1HxvzrD1_nwXc4zPTTRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);